/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package InterfaceIHM;

/**
 *
 * @author Héloïse
 */
public class FormAddArticle extends javax.swing.JPanel {

    /**
     * Creates new form FormAddArticle
     */
    public FormAddArticle() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel2 = new javax.swing.JPanel();
        jLabelNom = new javax.swing.JLabel();
        jLabelImage = new javax.swing.JLabel();
        jLabelDescription = new javax.swing.JLabel();
        jLabelStock = new javax.swing.JLabel();
        jLabelFournisseur = new javax.swing.JLabel();
        jTextFieldNom = new javax.swing.JTextField();
        jTextFieldImage = new javax.swing.JTextField();
        jScrollPaneDescription = new javax.swing.JScrollPane();
        jTextAreaDescription = new javax.swing.JTextArea();
        jSpinnerStock = new javax.swing.JSpinner();
        jComboBoxFournisseur = new javax.swing.JComboBox<>();
        jButtonEnregistrer = new javax.swing.JButton();
        jButtonParcourir = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 204));
        setLayout(new java.awt.GridBagLayout());

        jPanel2.setBackground(new java.awt.Color(255, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 255), 4, true), javax.swing.BorderFactory.createTitledBorder(null, "Formulaire d'ajout article", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 3, 18)))); // NOI18N

        jLabelNom.setFont(new java.awt.Font("Goudy Old Style", 1, 14)); // NOI18N
        jLabelNom.setText("Nom:");

        jLabelImage.setFont(new java.awt.Font("Goudy Old Style", 1, 14)); // NOI18N
        jLabelImage.setText("Image:");

        jLabelDescription.setFont(new java.awt.Font("Goudy Old Style", 1, 14)); // NOI18N
        jLabelDescription.setText("Description:");

        jLabelStock.setFont(new java.awt.Font("Goudy Old Style", 1, 14)); // NOI18N
        jLabelStock.setText("Stock:");

        jLabelFournisseur.setFont(new java.awt.Font("Goudy Old Style", 1, 14)); // NOI18N
        jLabelFournisseur.setText("Fournisseur:");

        jTextFieldNom.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldNom.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextFieldNom.addActionListener(this::jTextFieldNomActionPerformed);

        jTextFieldImage.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldImage.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextFieldImage.addActionListener(this::jTextFieldImageActionPerformed);

        jScrollPaneDescription.setBackground(new java.awt.Color(255, 255, 255));

        jTextAreaDescription.setBackground(new java.awt.Color(204, 204, 204));
        jTextAreaDescription.setColumns(20);
        jTextAreaDescription.setLineWrap(true);
        jTextAreaDescription.setRows(5);
        jTextAreaDescription.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPaneDescription.setViewportView(jTextAreaDescription);

        jSpinnerStock.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jComboBoxFournisseur.setBackground(new java.awt.Color(204, 204, 204));
        jComboBoxFournisseur.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxFournisseur.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jComboBoxFournisseur.addActionListener(this::jComboBoxFournisseurActionPerformed);

        jButtonEnregistrer.setBackground(new java.awt.Color(204, 204, 204));
        jButtonEnregistrer.setFont(new java.awt.Font("Goudy Old Style", 1, 14)); // NOI18N
        jButtonEnregistrer.setText("Enregistrer");
        jButtonEnregistrer.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonEnregistrer.addActionListener(this::jButtonEnregistrerActionPerformed);

        jButtonParcourir.setBackground(new java.awt.Color(204, 204, 204));
        jButtonParcourir.setFont(new java.awt.Font("Goudy Old Style", 1, 14)); // NOI18N
        jButtonParcourir.setText("Parcourir");
        jButtonParcourir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonParcourir.addActionListener(this::jButtonParcourirActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelNom)
                                    .addComponent(jLabelImage))
                                .addGap(97, 97, 97)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldNom, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldImage, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(26, 26, 26)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelFournisseur)
                                            .addComponent(jLabelStock)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabelDescription)))
                                .addGap(67, 67, 67)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButtonParcourir, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPaneDescription, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                                    .addComponent(jSpinnerStock, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                                    .addComponent(jComboBoxFournisseur, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonEnregistrer, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNom))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldImage, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelImage))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonParcourir)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPaneDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jSpinnerStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelStock))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxFournisseur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelFournisseur)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabelDescription)))
                .addGap(18, 18, 18)
                .addComponent(jButtonEnregistrer)
                .addGap(64, 64, 64))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipady = 50;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 23, 6, 24);
        add(jPanel2, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomActionPerformed

    private void jButtonEnregistrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnregistrerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonEnregistrerActionPerformed

    private void jButtonParcourirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonParcourirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonParcourirActionPerformed

    private void jComboBoxFournisseurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxFournisseurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxFournisseurActionPerformed

    private void jTextFieldImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldImageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldImageActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEnregistrer;
    private javax.swing.JButton jButtonParcourir;
    private javax.swing.JComboBox<String> jComboBoxFournisseur;
    private javax.swing.JLabel jLabelDescription;
    private javax.swing.JLabel jLabelFournisseur;
    private javax.swing.JLabel jLabelImage;
    private javax.swing.JLabel jLabelNom;
    private javax.swing.JLabel jLabelStock;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPaneDescription;
    private javax.swing.JSpinner jSpinnerStock;
    private javax.swing.JTextArea jTextAreaDescription;
    private javax.swing.JTextField jTextFieldImage;
    private javax.swing.JTextField jTextFieldNom;
    // End of variables declaration//GEN-END:variables
}
